name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql/mysql-server:8.0
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: testing
          MYSQL_USER: root
          MYSQL_PASSWORD: password
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping -uroot -ppassword" --health-interval=10s --health-timeout=5s --health-retries=10

    env:
      DB_CONNECTION: mysql
      DB_HOST: localhost
      DB_PORT: 3306
      DB_DATABASE: testing
      DB_USERNAME: root
      DB_PASSWORD: password

    steps:
    - uses: actions/checkout@v4
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.2'
    - name: Install Dependencies
      run: |
        curl -sS https://getcomposer.org/installer | php -- --version=2.7.6
        sudo mv composer.phar /usr/local/bin/composer
        composer install --no-interaction --prefer-dist
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Generate key 
      run: php artisan key:generate 
    - name: Directory Permissions 
      run: chmod -R 777 storage bootstrap/cache
    - name: Run migrations
      run: php artisan migrate --seed

    - name: Run tests
      run: vendor/bin/pest

    - name: Analyze with PHPStan and Pint
      run: |
          vendor/bin/phpstan analyse --level=5 --memory-limit=1G
          vendor/bin/pint --preset psr12
